name = "ArraySignalProcessing"
uuid = "a518b6d9-4657-4662-af1b-f64c5ccf359f"
authors = ["Matthias Sch√∂n"]
version = "1.0.0-DEV"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
PRIMA = "0a7d04aa-8ac2-47b3-b7a7-9dbd6ad661ed"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
ProximalAlgorithms = "140ffc9f-1907-541a-a177-7475e0a401e9"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Convex = "0.16.4"
ForwardDiff = "1.0.1"
Interpolations = "0.16.1"
LinearAlgebra = "1.11.0"
Optim = "1.13.2"
Optimization = "4.5.0"
OptimizationOptimJL = "0.4.3"
PRIMA = "0.2.4"
Peaks = "0.5.3"
ProximalAlgorithms = "0.5.4"
ProximalOperators = "0.16.1"
Roots = "2.2.8"
SCS = "2.1.0"
StatsBase = "0.34.6"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
